### ISSUE TITLE
Single quotes added inside the html tag

### ISSUE THREAD

**Issue by PlkMarudny** [saikatdas0790/svelte-environment-variables#1]
Hi,

When I tried to to insert a string into the h1 tag like below:

````<h1>process.env.SVELTE_APP_TITLE</h1>````

I got the following after replacement:

````<h1 class="svelte-1xhiu5h">'Development'</h1>````

While in the console output:

````
console.log('environment: ', process.env.SVELTE_APP_TITLE);
> Development
````

From where those quotes come from?

I use .rc file, if this matters.

**Comment by PlkMarudny** [comment]
Oh, I can see now, it is in code. So basically what I have to do is to define a variable, and use Svelte to do the rest:

````
const TITLE = process.env.SVELTE_APP_TITLE;

<h1>{TITLE}</h1>
````

**Comment by saikatdas0790** [comment]
@PlkMarudny That's right. Think of the environment variables as JavaScript strings. So, in your Svelte markup, you will have to surround them with curly braces

You could also directly do this
```html
<h1>{process.env.SVELTE_APP_TITLE}</h1>
```
